apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetcore-web-app
  namespace: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dotnetcore-web-app
  template:
    metadata:
      labels:
        app: dotnetcore-web-app
    spec:
      containers:
      - name: dotnetcore-web-app
        image: orielias/my-dotnet-app:latest
        ports:
        - containerPort: 80
