apiVersion: apps/v1
kind: Deployment
metadata:
  name: dotnetcore-deploy
  namespace: deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dotnetcore-deploy
  template:
    metadata:
      labels:
        app: dotnetcore-deploy
    spec:
      containers:
      - name: dotnetcore-deploy
        image: orielias/my-dotnet-app:latest
        ports:
        - containerPort: 80
