apiVersion: v1
kind: Service
metadata:
  name: dotnetcore-service
  namespace: deploy
spec:
  type: NodePort
  selector:
    app: dotnetcore-deploy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
