apiVersion: v1
kind: Service
metadata:
  name: dotnetcore-service
  namespace: web-app
spec:
  type: NodePort
  selector:
    app: dotnetcore-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
