apiVersion: apps/v1
kind: Deployment
metadata: 
  name: jenkins
  namespace: devops
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes:
      - name: docker-sock-volume
        hostPath:
          path: /var/run/docker.sock
      - name: jenkins-data
        persistentVolumeClaim:
          claimName: local-pvc 
      containers:
      - name: jenkins
        image: orielias/jenkins-image:latest
        env:
        - name: DOCKER_HOST
          value: "tcp://54.89.152.36:2375"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: docker-sock-volume
          mountPath: /var/run/docker.sock
        - name: jenkins-data
          mountPath: /var/jenkins_home
